CREATE TABLE book (
    id UUID PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    price NUMERIC(19, 2) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('PUBLISHED', 'UNPUBLISHED')) DEFAULT 'PUBLISHED',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE OR REPLACE FUNCTION prevent_status_revert()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status = 'PUBLISHED' AND NEW.status = 'UNPUBLISHED' THEN
        RAISE EXCEPTION 'Cannot change status from PUBLISHED to UNPUBLISHED.';
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_prevent_status_revert
    BEFORE UPDATE ON book
    FOR EACH ROW
    WHEN (OLD.status IS DISTINCT FROM NEW.status)
    EXECUTE FUNCTION prevent_status_revert();